### ISSUE TITLE
replace serveo.net

### ISSUE THREAD

**Issue by rbaynes** [OpenAgInitiative/openag-device-software#125]
serveo.net can go down for days, which kills our remote support plans.

Rob has pricing ($100/month for 100 installs) of ngrok link https://ngrok.com/docs/ngrok-link and approval from Caleb.

The issue we want to ship by default with the free serveo.net.   Then with a special device UI provision step, we want to overwrite serveo.net usage with ngrok link.    

AND we don't want to check into our github repo any of the ngrok license info - we should prompt for it in the device UI provision step.   We don't want anyone using the code in our (soon to be) public repo to use our ngrok licenses we pay for.

**Comment by jakerye** [comment]
serveo is fine for a default solution. the better version of this is using a service like mender or balena for high value devices. but will be installed on a per-app basis and does not need to be integrated into the standard code base
