### ISSUE TITLE
Simplify & improve the provision / registration process

### ISSUE THREAD

**Issue by rbaynes** [OpenAgInitiative/openag-device-software#145]
# New S/N format and central ID storage
- We will use a single number for everything the user sees.  It will be a serial number in this format: "PFC_EDU-XXXX" where the XXXX is the 4 digit BBB  access point code (if on eth, use eeprom code).
- Store provisioned IDs in `/etc/openagbrain/serial_number.json`
  - `"AP_number": "XXXX"`
  - `"eeprom": "ABCDEF123"`  (perhaps don't use for serveo/ngrok link?  use shorter AP code?)
  - `"serial_number": "PFC_EDU-XXXX"` (XXXX is AP_number)
  - `"deviceID": "EDU-$CKSUM-$MAC"` (from the IoT reg script)

# Create a new Provision page (in the provision drop menu)
- Page checks if device is online, if not, prompt user to go to (link) Connect page and hide everything.
- There is a one time use "Provision this device" button that is shown if there is no `/etc/openagbrain/serial_number.json` file.
- Provision button creates `/etc/openagbrain/serial_number.json` and does the public IoT reg (runs the script).
- Page shows the generated info when done for information only (for us).

# New single number (S/N) procedures
- We now label the EDU with a single number, just the S/N described above.
- In the header (or footer) of the device UI, we show the S/N and the debian package version (for quick and easy support)

# Change default BBBs AP name and password
- In our flasher image, change the default BBBw AP name to our S/N, password to `openag`
- Should the **Change password** page also change the AP password?

# Password protected OpenAg only ngrok paid client provision step
- Rob has to play with ngrok link and get some answers from them about how their auth step works.
- This will fix #125

**Comment by wsokno** [comment]
How & why the SSID gets set:

1. The BeagleBone-XXXX SSID is set by the `/usr/bin/bb-wl18xx-wlan0` service which calls `/usr/bin/bb-wl18xx-tether` which takes default configuration values from `/etc/default/bb-wl18xx`. In particular, `bb-wl18xx` sets:
   
   ```
   USE_PERSONAL_SSID="BeagleBone"
   USE_PERSONAL_PASSWORD="BeagleBone"
   USE_APPENDED_SSID=yes
   ```

2. If you want to set the SSID to a specific fixed value, something like this in `/etc/default/bb-wl18xx` will probably work:

   ```
   USE_PERSONAL_SSID="whatever"
   USE_APPENDED_SSID=no
   ```

3. The appended SSID suffix is calculated in `/usr/bin/bb-wl18xx-tether` which is a complex bash script. By my reading, the XXXX suffix appears to come from [this line](https://github.com/RobertCNelson/bb-wl18xx-firmware/blob/bc40786f9268a23107afe3a43a1f87d330fc83d5/debian/bb-wl18xx-tether#L344)

   ```
   ssid_append=$(echo ${use_mac} | cut -b 13-17 | sed 's/://g' || true)
   ```
   
   in the `start_hostapd` function, or perhaps from [a similar line](https://github.com/RobertCNelson/bb-wl18xx-firmware/blob/bc40786f9268a23107afe3a43a1f87d330fc83d5/debian/bb-wl18xx-tether#L108) in the `connmanctl_tether_wifi_on` function. It looks like that stuff is just taking the last 4 hex digits of the mac address without the colon. For example:

   ```
   $ echo 'aa:bb:cc:dd:ee:ff' | cut -b 13-17 | sed 's/://g'
   eeff
   ```

   The value of `use_mac` comes from `cpsw3_mac` which gets set in the [`wait_for_mac` function](https://github.com/RobertCNelson/bb-wl18xx-firmware/blob/bc40786f9268a23107afe3a43a1f87d330fc83d5/debian/bb-wl18xx-tether#L186-L201). I'm not sure what that function is doing in the midde, but it starts by trying to get an ethernet MAC address out of `/proc/device-tree/...`.


Background Links:
- https://github.com/rcn-ee/repos/blob/master/bb-wl18xx-firmware/suite/stretch/debian/bb-wl18xx-wlan0.service
- https://github.com/rcn-ee/repos/blob/master/bb-wl18xx-firmware/suite/stretch/debian/bb-wl18xx-wlan0
- https://github.com/rcn-ee/repos/blob/master/bb-wl18xx-firmware/suite/stretch/debian/bb-wl18xx-tether
- https://groups.google.com/forum/#!topic/beagleboard/KXGl8QprzsM
- https://www.element14.com/community/roadTestReviews/2390/l/beagleboardorg-bbb-wireless-bbbwl-sc-562-review

**Comment by jakerye** [comment]
this is no longer pertinent. upon the next production roll out, the provisioning and registration flow should be re-examined to support a platform agnostic flow
