### ISSUE TITLE
Move bash script logic used in managers and utilities into python functions

### ISSUE THREAD

**Issue by jakerye** [OpenAgInitiative/openag-device-software#166]
Wherever is reasonable, move logic from bash scripts into python so we don't have to call bash scripts from python.

This will make the logic cleaner / more robust (e.g. able to catch exceptions and have code in 2 places)

**Comment by rbaynes** [comment]
Good idea.  But for some things we still need to start a script to manually
do things:
- register as an IoT device
- list wifi APs
- connect to a wifi AP
- set mux, scan, LEDs on/off/fade

I think that is all I ever use manually.  Oh, and we need scripts for the
stuff we call from upgrade: pip, collectstatic, etc.


Thanks,
Rob Baynes
*pronouns: he / him / his*

**Comment by jakerye** [comment]
Most of this has been accomplished in the latest installation process refactor
