### ISSUE TITLE
device UI peripheral buttons not working,  master branch

### ISSUE THREAD

**Issue by rbaynes** [OpenAgInitiative/openag-device-software#172]
On the peripherals page of the device UI, running from master on a real EDU with v0.3.0 config.
When I use the "set sampling interval" on the Camera, I see this in the output and nothing happens:
```
Not Found: /api/event/
[05/Nov/2018 16:49:36] "POST /api/event/ HTTP/1.1" 404 21515
```

**Comment by jakerye** [comment]
fixed in cbf2b5d0ac2076c53f02286149c5df162ba8301b
