### ISSUE TITLE
publish balena remote URL with IoT boot message

### ISSUE THREAD

**Issue by rbaynes** [OpenAgInitiative/openag-device-software#235]
For now, all balena applications we deploy should have that public remote URL enabled, and we should publish it in the boot message as remote_URL.  That way in the Admin UI, we can click it to get to the device UI directly.

boot message 2019-04-09T19:45:42Z
```
{"device_config": "pfc3-v0.3.0-picam", "package_version": null, "IP": "172.17.0.166", "access_point": "unknown", "serial_number": "green-frog", "remote_URL": "", "bbb_serial": "DEPRECATED"}
```

**Comment by srmoore** [comment]
No way to enable the public url by default, but from Balena you can "enable all public urls" for devices already added to the application under the "Actions" tab on the left.
