### ISSUE TITLE
handle published command to upgrade debian package

### ISSUE THREAD

**Issue by rbaynes** [OpenAgInitiative/openag-device-software#96]
Cloud UI can publish a message to the JBrain to do an upgrade to the latest package.  JBrain IoT manager should tell the UpgradeManager (or use UpgradeUtils.update_software()) to do the upgrade.

Related to #85 which tells the backend when it has an available upgrade.

**Comment by jakerye** [comment]
Upgrades should go through a managed iot ota system. Debian packages too prone to brick. See mender or balena
